import {describe,it,expect} from 'vitest';
import {isModelsLeaderboardResponse,isModelsDetailResponse} from './models-types';
import {priceSummary} from './model-prices';
import leaderboard from './fixtures/leaderboard.json';
import deepseek from './fixtures/deepseek.json';
import astra from './fixtures/astra.json';
import qwen from './fixtures/qwen.json';
// Generated by backend buildApp.inject from its migrated fixture DB, not hand-authored wire shapes.
describe('backend price wire contract',()=>{
  it('accepts all released models from the additive backend response',()=>{expect(isModelsLeaderboardResponse(leaderboard,'overall','released')).toBe(true);expect(leaderboard.items).toHaveLength(50);});
  it('accepts fixed, tiered and unknown detail payloads',()=>{for(const d of [deepseek,astra,qwen])expect(isModelsDetailResponse(d)).toBe(true);});
  it('shows retained legacy USD prices and genuine peak/offpeak range',()=>{if(!isModelsDetailResponse(deepseek)||!isModelsDetailResponse(astra))throw new Error('contract');expect(priceSummary(deepseek.price)[0]).toContain('–');expect(priceSummary(astra.price)).toEqual(['—']);});
});

it.each([undefined,null,"2027-01-01T00:00:00.000Z"])("accepts an additive global value deadline %s", deadline=>{
  expect(isModelsDetailResponse({...deepseek,meta:{...deepseek.meta,valueValidUntil:deadline}})).toBe(true);
  expect(isModelsLeaderboardResponse({...leaderboard,meta:{...leaderboard.meta,valueValidUntil:deadline}})).toBe(true);
});
it.each([42,"not-a-date",{}])("rejects an invalid global value deadline %j",deadline=>{
  expect(isModelsDetailResponse({...deepseek,meta:{...deepseek.meta,valueValidUntil:deadline}})).toBe(false);
  expect(isModelsLeaderboardResponse({...leaderboard,meta:{...leaderboard.meta,valueValidUntil:deadline}})).toBe(false);
});
