import {describe,it,expect} from 'vitest';
import {findPath,initialGrid} from './pathfinding';
import {delaunay,voronoiCells} from './geometry';
import {createCloth,cutCloth,stepCloth} from './cloth';
import {createRaft,tickRaft,appendRaft,toggleRaftNode,type RaftState} from './raft';
const run=(state:RaftState,count=30)=>{for(let i=0;i<count;i++)state=tickRaft(state);return state;};
describe('pathfinding',()=>{
  it('finds equally short legal paths with fewer A* visits',()=>{const map=initialGrid(),a=findPath(map,'astar'),d=findPath(map,'dijkstra');expect(a.path.length).toBe(d.path.length);expect(a.visited.length).toBeLessThan(d.visited.length);expect(a.path[0]).toBe(map.start);expect(a.path.at(-1)).toBe(map.end);for(let i=1;i<a.path.length;i++){const prev=a.path[i-1],n=a.path[i];expect(map.walls).not.toContain(n);expect(Math.abs(n%map.cols-prev%map.cols)+Math.abs(Math.floor(n/map.cols)-Math.floor(prev/map.cols))).toBe(1);}});
  it('does not wrap rows and reports unreachable/end=start',()=>{expect(findPath({cols:3,rows:2,start:2,end:3,walls:[0,1,4,5]},'astar').path).toEqual([]);expect(findPath({cols:1,rows:1,start:0,end:0,walls:[]},'astar').path).toEqual([0]);});
  it('matches Dijkstra on deterministic obstacle maps',()=>{for(let seed=0;seed<30;seed++){const map={cols:20,rows:12,start:0,end:239,walls:Array.from({length:238},(_,i)=>i+1).filter(i=>((i*733+seed*997)%113)<29)};expect(findPath(map,'astar').path.length).toBe(findPath(map,'dijkstra').path.length);}});
});
describe('geometry',()=>{
  it('handles insufficient, duplicate and collinear points',()=>{expect(delaunay([]).triangles).toEqual([]);expect(delaunay([{x:0,y:0},{x:0,y:0},{x:1,y:1},{x:2,y:2}]).triangles).toEqual([]);expect(voronoiCells([{x:1,y:1}],10,10)[0]).toHaveLength(4);expect(voronoiCells([{x:2,y:2},{x:8,y:2}],10,10)).toHaveLength(2);});
  it('triangulates square and partitions its rectangle without area loss',()=>{const points=[{x:2,y:2},{x:8,y:2},{x:8,y:8},{x:2,y:8}];expect(delaunay(points).triangles).toHaveLength(2);const area=voronoiCells(points,10,10).reduce((sum,cell)=>sum+Math.abs(cell.reduce((s,p,i)=>{const q=cell[(i+1)%cell.length];return s+p.x*q.y-p.y*q.x;},0))/2,0);expect(area).toBeCloseTo(100,6);});
  it('every returned cell vertex is closest to its site',()=>{const points=Array.from({length:20},(_,i)=>({x:(i*37)%100,y:(i*63)%91}));const cells=voronoiCells(points,100,100);cells.forEach((cell,i)=>cell.forEach(p=>{const distance=Math.hypot(p.x-points[i].x,p.y-points[i].y);for(const q of points)expect(distance).toBeLessThanOrEqual(Math.hypot(p.x-q.x,p.y-q.y)+1e-5);}));});
});
describe('XPBD cloth',()=>{
  it('keeps pins and finite bounded positions while progressing time',()=>{const c=createCloth(),pins=c.points.filter(p=>p.pinned).map(p=>({...p}));for(let i=0;i<120;i++)stepCloth(c,{wind:2,obstacle:true,grab:null});expect(c.time).toBeCloseTo(2);expect(c.points.filter(p=>p.pinned)).toEqual(pins);for(const p of c.points){expect(Number.isFinite(p.x)&&Number.isFinite(p.y)).toBe(true);expect(p.x).toBeGreaterThanOrEqual(5);expect(p.y).toBeLessThanOrEqual(355);}});
  it('cuts segment interiors and preserves tears across steps',()=>{const c=createCloth(),l=c.links[250],a=c.points[l.a],b=c.points[l.b];cutCloth(c,(a.x+b.x)/2,(a.y+b.y)/2,2);expect(l.active).toBe(false);stepCloth(c,{wind:0,obstacle:false,grab:null});expect(l.active).toBe(false);expect(createCloth().links.every(l=>l.active)).toBe(true);});
  it('grab has zero inverse mass during constraint iterations',()=>{const c=createCloth();stepCloth(c,{wind:3,obstacle:true,grab:{id:50,x:200,y:160}});expect(c.points[50].x).toBe(200);expect(c.points[50].y).toBe(160);});
});
describe('Raft protocol',()=>{
  it('elects one leader and commits replicated entries',()=>{let s=run(createRaft());const leaders=s.nodes.filter(n=>n.role==='leader');expect(leaders).toHaveLength(1);s=run(appendRaft(s,leaders[0].id,'x=1'),5);expect(s.nodes.every(n=>n.commit===2&&n.log[1].value==='x=1')).toBe(true);});
  it('minority cannot commit and reconnect repairs divergent suffixes',()=>{let s=run(createRaft());const leader=s.nodes.find(n=>n.role==='leader')!;const peer=(leader.id+1)%5;s.groups=s.nodes.map(n=>n.id===leader.id||n.id===peer?1:0);s=run(appendRaft(s,leader.id,'isolated'),25);expect(s.nodes[leader.id].commit).toBe(1);const major=s.nodes.find(n=>n.role==='leader'&&s.groups[n.id]===0)!;expect(major).toBeDefined();s=run(appendRaft(s,major.id,'majority'),5);expect(s.nodes[major.id].commit).toBeGreaterThan(1);s.groups=[0,0,0,0,0];s=run(s,40);expect(s.nodes.filter(n=>n.role==='leader')).toHaveLength(1);const logs=s.nodes.map(n=>JSON.stringify(n.log));expect(new Set(logs).size).toBe(1);expect(s.nodes[0].log.some(e=>e.value==='isolated')).toBe(false);expect(s.nodes.every(n=>n.log.some(e=>e.value==='majority'))).toBe(true);});
  it('replaces a failed leader while retaining committed prefix',()=>{let s=run(createRaft());const id=s.nodes.find(n=>n.role==='leader')!.id;s=run(appendRaft(s,id,'stable'));s=run(toggleRaftNode(s,id));expect(s.nodes.filter(n=>n.alive&&n.role==='leader')).toHaveLength(1);s=run(toggleRaftNode(s,id));expect(s.nodes.every(n=>n.log[1].value==='stable'&&n.commit>=2)).toBe(true);});
  it('never commits with only two live nodes',()=>{let s=createRaft();s=toggleRaftNode(toggleRaftNode(toggleRaftNode(s,2),3),4);s=run(s,60);expect(s.nodes.every(n=>n.commit===0&&n.role!=='leader')).toBe(true);});
});
